#!/usr/bin/env python
# -*- coding: utf-8 -*-


# nctime.utils.constants.AVERAGE_CORRECTION_FREQ
AVERAGE_CORRECTION_FREQ = ["day", "mon", "monPt", "yr", "yrPt", "1hrCM", "sem"]


# (table_id, frequency) -> (value, unit)

FREQ_INC = {
    ("None", "subhr"): (30, "minutes"),
    ("None", "subhrPt"): (30, "minutes"),
    ("None", "1hr"): (1, "hours"),
    ("None", "1hrCM"): (1, "hours"),
    ("None", "1hrPt"): (1, "hours"),
    ("None", "3hr"): (3, "hours"),
    ("None", "3hrPt"): (3, "hours"),
    ("None", "6hr"): (6, "hours"),
    ("None", "6hrPt"): (6, "hours"),
    ("None", "day"): (1, "days"),
    ("None", "dec"): (10, "years"),
    ("None", "mon"): (1, "months"),
    ("None", "monC"): (1, "months"),
    ("None", "monPt"): (1, "months"),
    ("None", "sem"): (3, "months"),
    ("None", "yr"): (1, "years"),
    ("None", "yrPt"): (1, "years"),
    ("3hr", "3hr"): [3, "hours"],
    ("3hr", "3hrPt"): [3, "hours"],
    ("3hrCurt", "3hr"): [3, "hours"],
    ("3hrMlev", "3hr"): [3, "hours"],
    ("3hrPlev", "3hr"): [3, "hours"],
    ("3hrSlev", "3hr"): [3, "hours"],
    ("6hrLev", "6hrPt"): [6, "hours"],
    ("6hrLev", "6hr"): [6, "hours"],
    ("6hrPlev", "6hr"): [6, "hours"],
    ("6hrPlevPt", "6hr"): [6, "hours"],
    ("6hrPlevPt", "6hrPt"): [6, "hours"],
    ("Aclim", "monClim"): [1, "months"],
    ("AERday", "day"): [1, "days"],
    ("AERhr", "1hr"): [1, "hours"],
    ("AERmon", "mon"): [1, "months"],
    ("AERmonZ", "mon"): [1, "months"],
    ("aero", "mon"): [1, "months"],
    ("Amon", "mon"): [1, "months"],
    ("Amon", "monC"): [1, "months"],
    ("Amon", "monClim"): [1, "months"],
    ("AmonExtras", "mon"): [1, "months"],
    ("CF3hr", "3hrPt"): [3, "hours"],
    ("cf3hr", "3hr"): [3, "hours"],
    ("CFday", "day"): [1, "days"],
    ("cfDay", "day"): [1, "days"],
    ("CFmon", "mon"): [1, "months"],
    ("cfMon", "mon"): [1, "months"],
    ("cfOff", "mon"): [1, "months"],
    ("cfSites", "3hr"): [3, "hours"],
    ("cfSites", "6hr"): [6, "hours"],
    ("cfSites", "subhr"): [30, "minutes"],
    ("CFsubhr", "subhrPt"): [30, "minutes"],
    ("day", "day"): [1, "days"],
    ("dayExtras", "day"): [1, "days"],
    ("E1hr", "1hr"): [1, "hours"],
    ("E1hr", "1hrPt"): [1, "hours"],
    ("E1hrClimMon", "1hrCM"): [1, "hours"],
    ("E3hr", "3hr"): [3, "hours"],
    ("E3hrPt", "3hrPt"): [3, "hours"],
    ("E6hrZ", "6hr"): [6, "hours"],
    ("E6hrZ", "6hrPt"): [6, "hours"],
    ("Eday", "day"): [1, "days"],
    ("EdayZ", "day"): [1, "days"],
    ("Emon", "mon"): [1, "months"],
    ("EmonZ", "mon"): [1, "months"],
    ("Esubhr", "subhrPt"): [30, "minutes"],
    ("Eyr", "yr"): [1, "years"],
    ("Eyr", "yrPt"): [1, "years"],
    ("ImonAnt", "mon"): [1, "months"],
    ("ImonGre", "mon"): [1, "months"],
    ("IyrAnt", "yr"): [1, "years"],
    ("IyrGre", "yr"): [1, "years"],
    ("Lclim", "monClim"): [1, "months"],
    ("LIclim", "monClim"): [1, "months"],
    ("LImon", "mon"): [1, "months"],
    ("Lmon", "mon"): [1, "months"],
    ("Oclim", "monClim"): [1, "months"],
    ("Oclim", "monC"): [1, "months"],
    ("Oday", "day"): [1, "days"],
    ("Odec", "dec"): [10, "years"],
    ("OIclim", "monClim"): [1, "months"],
    ("OImon", "mon"): [1, "months"],
    ("Omon", "mon"): [1, "months"],
    ("OmonExtras", "mon"): [1, "months"],
    ("Oyr", "yr"): [1, "years"],
    ("OyrExtras", "yr"): [1, "years"],
    ("SIday", "day"): [1, "days"],
    ("SImon", "mon"): [1, "months"],
    ("SImon", "monPt"): [1, "months"],
    ("sites", "subhr"): [30, "minutes"],
    ("HOMAL3hrPt", "3hrPt"): [3, "hours"],
    ("HOMAL3hrPt", "3hr"): [3, "hours"],
    ("HOMALmon", "mon"): [1, "months"],
    ("HOMEPmon", "mon"): [1, "months"],
    ("HOMOImon", "mon"): [1, "months"],
}
